# Generated by Django 5.0.2 on 2025-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0002_remove_editsession_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="editsession",
            name="server_id",
            field=models.UUIDField(default=None, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
