# Generated by Django 5.0.2 on 2025-05-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0003_editsession_server_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editsession",
            name="server_id",
            field=models.UUIDField(editable=False),
        ),
    ]
